CREATE TABLE public.reviews (
    id bigint NOT NULL,
    tutoring_id uuid NOT NULL,
    user_id uuid NOT NULL,
    rating smallint NOT NULL,
    comment text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.reviews OWNER TO postgres;

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_tutoring_id_fkey FOREIGN KEY (tutoring_id) REFERENCES public.tutorings(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE public.reviews
    ADD CONSTRAINT rating_check CHECK ((rating >= 1) AND (rating <= 5));

-- Add a unique constraint to ensure a user can only review a tutoring once.
ALTER TABLE public.reviews ADD CONSTRAINT unique_review UNIQUE (tutoring_id, user_id);

-- Enable RLS
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Policies for reviews
CREATE POLICY "Allow read access to everyone" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Allow insert access to authenticated users" ON public.reviews FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow update access to owner" ON public.reviews FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Allow delete access to owner" ON public.reviews FOR DELETE USING (auth.uid() = user_id);
